# Azure DevOps Pipeline for CI/CD Integration

trigger:
  branches:
    include:
      - feature/pythonapp

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
  DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)
  IMAGE_NAME: 'gald10102/flask-aws-monitor'

stages:
- stage: CloneRepository
  displayName: 'Clone Repository'
  jobs:
  - job: Clone
    steps:
    - checkout: self

- stage: ParallelChecks
  displayName: 'Parallel Linting & Security Checks'
  dependsOn: CloneRepository
  jobs:
  - job: Linting
    displayName: 'Linting'
    steps:
      - script: echo "linting"
        displayName: 'Run Linting'

  - job: SecurityScanning
    displayName: 'Security Scanning'
    steps:
      - script: echo echo "security scan"
        displayName: 'Run Security Scan'

- stage: BuildDockerImage
  displayName: 'Build Docker Image'
  dependsOn: ParallelChecks
  jobs:
  - job: BuildImage
    steps:
      - script: echo "build docker"
        displayName: 'Build Docker Image'

- stage: PushToDockerHub
  displayName: 'Push Docker Image to Docker Hub'
  dependsOn: BuildDockerImage
  jobs:
  - job: PushImage
    steps:
      - script: |
          docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)
          docker build -t $(IMAGE_NAME) .
          docker push $(IMAGE_NAME)
        displayName: 'Push Docker Image to Docker Hub'

- stage: SecureCredentials
  displayName: 'Store and Use Secure Credentials'
  dependsOn: []
  jobs:
  - job: StoreSecrets
    displayName: 'Ensure Credentials are Secure'
    steps:
      - script: |
          echo 'TODO: Configure Azure DevOps secrets for Docker Hub login'
          echo 'Use Azure DevOps secure variable groups for storing credentials securely'
        displayName: 'Secure Credential Storage'
